FROM tiangolo/uvicorn-gunicorn:python3.11-slim

LABEL maintainer="Angel A. Garcia Gonzalez <angelgarcia@idom.com>"

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH $PWD

COPY requirements.txt /tmp/requirements.txt

# install python dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY . .

EXPOSE 8000

# CMD ["/start.dev.sh"]