"""init

Revision ID: 0bb726f45abd
Revises: 
Create Date: 2023-07-21 15:52:39.653603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb726f45abd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indu_emisiones_gases_efecto_invernadero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_emisiones_gases_efecto_invernadero_id'), 'indu_emisiones_gases_efecto_invernadero', ['id'], unique=False)
    op.create_table('indu_emisiones_por_el_consumo_de_bagazo_y_otros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_emisiones_por_el_consumo_de_bagazo_y_otros_id'), 'indu_emisiones_por_el_consumo_de_bagazo_y_otros', ['id'], unique=False)
    op.create_table('indu_emisiones_sao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_emisiones_sao_id'), 'indu_emisiones_sao', ['id'], unique=False)
    op.create_table('indu_salidas_por_combustible_balance_total_de_la_energia_requerida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_salidas_por_combustible_balance_total_de_la_energia_requerida_id'), 'indu_salidas_por_combustible_balance_total_de_la_energia_requerida', ['id'], unique=False)
    op.create_table('indu_salidas_por_combustible_energia_producida_por_autogeneracion_y_cogeneracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_salidas_por_combustible_energia_producida_por_autogeneracion_y_cogeneracion_id'), 'indu_salidas_por_combustible_energia_producida_por_autogeneracion_y_cogeneracion', ['id'], unique=False)
    op.create_table('indu_salidas_por_combustible_energia_requerida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_salidas_por_combustible_energia_requerida_id'), 'indu_salidas_por_combustible_energia_requerida', ['id'], unique=False)
    op.create_table('indu_salidas_por_tipo_de_industria_balance_total_de_la_energia_requerida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_salidas_por_tipo_de_industria_balance_total_de_la_energia_requerida_id'), 'indu_salidas_por_tipo_de_industria_balance_total_de_la_energia_requerida', ['id'], unique=False)
    op.create_table('indu_salidas_por_tipo_de_industria_energia_producida_por_autogeneracion_y_cogeneracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_salidas_por_tipo_de_industria_energia_producida_por_autogeneracion_y_cogeneracion_id'), 'indu_salidas_por_tipo_de_industria_energia_producida_por_autogeneracion_y_cogeneracion', ['id'], unique=False)
    op.create_table('indu_salidas_por_tipo_de_industria_energia_requerida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('medida_1', sa.Integer(), nullable=True),
    sa.Column('medida_2', sa.Integer(), nullable=True),
    sa.Column('medida_3', sa.Integer(), nullable=True),
    sa.Column('medida_4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_salidas_por_tipo_de_industria_energia_requerida_id'), 'indu_salidas_por_tipo_de_industria_energia_requerida', ['id'], unique=False)
    op.create_table('indu_sf_capacidad_instalada_de_autogeneracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_capacidad_instalada_de_autogeneracion_id'), 'indu_sf_capacidad_instalada_de_autogeneracion', ['id'], unique=False)
    op.create_table('indu_sf_capacidad_instalada_de_cogeneracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_capacidad_instalada_de_cogeneracion_id'), 'indu_sf_capacidad_instalada_de_cogeneracion', ['id'], unique=False)
    op.create_table('indu_sf_distribucion_segun_tipo_de_combustible_ladrilleras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_distribucion_segun_tipo_de_combustible_ladrilleras_id'), 'indu_sf_distribucion_segun_tipo_de_combustible_ladrilleras', ['id'], unique=False)
    op.create_table('indu_sf_emision_de_sao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_emision_de_sao_id'), 'indu_sf_emision_de_sao', ['id'], unique=False)
    op.create_table('indu_sf_excedentes_de_autogeneracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_excedentes_de_autogeneracion_id'), 'indu_sf_excedentes_de_autogeneracion', ['id'], unique=False)
    op.create_table('indu_sf_excedentes_de_cogeneracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_excedentes_de_cogeneracion_id'), 'indu_sf_excedentes_de_cogeneracion', ['id'], unique=False)
    op.create_table('indu_sf_factor_de_utilizacion_de_autogeneracion_y_cogeneracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_factor_de_utilizacion_de_autogeneracion_y_cogeneracion_id'), 'indu_sf_factor_de_utilizacion_de_autogeneracion_y_cogeneracion', ['id'], unique=False)
    op.create_table('indu_sf_indice_de_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_indice_de_consumo_id'), 'indu_sf_indice_de_consumo', ['id'], unique=False)
    op.create_table('indu_sf_produccion_anual_de_ladrillos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_produccion_anual_de_ladrillos_id'), 'indu_sf_produccion_anual_de_ladrillos', ['id'], unique=False)
    op.create_table('indu_sf_produccion_anual_de_materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_produccion_anual_de_materiales_id'), 'indu_sf_produccion_anual_de_materiales', ['id'], unique=False)
    op.create_table('indu_sf_produccion_de_acido_nitrico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_produccion_de_acido_nitrico_id'), 'indu_sf_produccion_de_acido_nitrico', ['id'], unique=False)
    op.create_table('indu_sf_produccion_de_cemento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_produccion_de_cemento_id'), 'indu_sf_produccion_de_cemento', ['id'], unique=False)
    op.create_table('indu_sf_uso_energetico_por_combustible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_sf_uso_energetico_por_combustible_id'), 'indu_sf_uso_energetico_por_combustible', ['id'], unique=False)
    op.create_table('indu_st_eficiencia_energetica_autogeneracion_y_cogeneracion_ladrilleras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('trayectoria', sa.Integer(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_st_eficiencia_energetica_autogeneracion_y_cogeneracion_ladrilleras_id'), 'indu_st_eficiencia_energetica_autogeneracion_y_cogeneracion_ladrilleras', ['id'], unique=False)
    op.create_table('indu_st_eficiencia_energetica_crecimiento_de_autogeneracion_y_cogeneracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('trayectoria', sa.Integer(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_st_eficiencia_energetica_crecimiento_de_autogeneracion_y_cogeneracion_id'), 'indu_st_eficiencia_energetica_crecimiento_de_autogeneracion_y_cogeneracion', ['id'], unique=False)
    op.create_table('indu_st_eficiencia_energetica_reduccion_de_consumo_energetico_ladrilleras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('trayectoria', sa.Integer(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_st_eficiencia_energetica_reduccion_de_consumo_energetico_ladrilleras_id'), 'indu_st_eficiencia_energetica_reduccion_de_consumo_energetico_ladrilleras', ['id'], unique=False)
    op.create_table('indu_st_procesos_productivos_sostenibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('trayectoria', sa.Integer(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_st_procesos_productivos_sostenibles_id'), 'indu_st_procesos_productivos_sostenibles', ['id'], unique=False)
    op.create_table('indu_st_reduccion_de_consumo_energetico_por_aumento_en_la_eficiencia_energetica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('trayectoria', sa.Integer(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_st_reduccion_de_consumo_energetico_por_aumento_en_la_eficiencia_energetica_id'), 'indu_st_reduccion_de_consumo_energetico_por_aumento_en_la_eficiencia_energetica', ['id'], unique=False)
    op.create_table('indu_st_sustitucion_de_sao_y_hfc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('trayectoria', sa.Integer(), nullable=True),
    sa.Column('2018', sa.Float(), nullable=True),
    sa.Column('2020', sa.Float(), nullable=True),
    sa.Column('2025', sa.Float(), nullable=True),
    sa.Column('2030', sa.Float(), nullable=True),
    sa.Column('2035', sa.Float(), nullable=True),
    sa.Column('2040', sa.Float(), nullable=True),
    sa.Column('2045', sa.Float(), nullable=True),
    sa.Column('2050', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indu_st_sustitucion_de_sao_y_hfc_id'), 'indu_st_sustitucion_de_sao_y_hfc', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_indu_st_sustitucion_de_sao_y_hfc_id'), table_name='indu_st_sustitucion_de_sao_y_hfc')
    op.drop_table('indu_st_sustitucion_de_sao_y_hfc')
    op.drop_index(op.f('ix_indu_st_reduccion_de_consumo_energetico_por_aumento_en_la_eficiencia_energetica_id'), table_name='indu_st_reduccion_de_consumo_energetico_por_aumento_en_la_eficiencia_energetica')
    op.drop_table('indu_st_reduccion_de_consumo_energetico_por_aumento_en_la_eficiencia_energetica')
    op.drop_index(op.f('ix_indu_st_procesos_productivos_sostenibles_id'), table_name='indu_st_procesos_productivos_sostenibles')
    op.drop_table('indu_st_procesos_productivos_sostenibles')
    op.drop_index(op.f('ix_indu_st_eficiencia_energetica_reduccion_de_consumo_energetico_ladrilleras_id'), table_name='indu_st_eficiencia_energetica_reduccion_de_consumo_energetico_ladrilleras')
    op.drop_table('indu_st_eficiencia_energetica_reduccion_de_consumo_energetico_ladrilleras')
    op.drop_index(op.f('ix_indu_st_eficiencia_energetica_crecimiento_de_autogeneracion_y_cogeneracion_id'), table_name='indu_st_eficiencia_energetica_crecimiento_de_autogeneracion_y_cogeneracion')
    op.drop_table('indu_st_eficiencia_energetica_crecimiento_de_autogeneracion_y_cogeneracion')
    op.drop_index(op.f('ix_indu_st_eficiencia_energetica_autogeneracion_y_cogeneracion_ladrilleras_id'), table_name='indu_st_eficiencia_energetica_autogeneracion_y_cogeneracion_ladrilleras')
    op.drop_table('indu_st_eficiencia_energetica_autogeneracion_y_cogeneracion_ladrilleras')
    op.drop_index(op.f('ix_indu_sf_uso_energetico_por_combustible_id'), table_name='indu_sf_uso_energetico_por_combustible')
    op.drop_table('indu_sf_uso_energetico_por_combustible')
    op.drop_index(op.f('ix_indu_sf_produccion_de_cemento_id'), table_name='indu_sf_produccion_de_cemento')
    op.drop_table('indu_sf_produccion_de_cemento')
    op.drop_index(op.f('ix_indu_sf_produccion_de_acido_nitrico_id'), table_name='indu_sf_produccion_de_acido_nitrico')
    op.drop_table('indu_sf_produccion_de_acido_nitrico')
    op.drop_index(op.f('ix_indu_sf_produccion_anual_de_materiales_id'), table_name='indu_sf_produccion_anual_de_materiales')
    op.drop_table('indu_sf_produccion_anual_de_materiales')
    op.drop_index(op.f('ix_indu_sf_produccion_anual_de_ladrillos_id'), table_name='indu_sf_produccion_anual_de_ladrillos')
    op.drop_table('indu_sf_produccion_anual_de_ladrillos')
    op.drop_index(op.f('ix_indu_sf_indice_de_consumo_id'), table_name='indu_sf_indice_de_consumo')
    op.drop_table('indu_sf_indice_de_consumo')
    op.drop_index(op.f('ix_indu_sf_factor_de_utilizacion_de_autogeneracion_y_cogeneracion_id'), table_name='indu_sf_factor_de_utilizacion_de_autogeneracion_y_cogeneracion')
    op.drop_table('indu_sf_factor_de_utilizacion_de_autogeneracion_y_cogeneracion')
    op.drop_index(op.f('ix_indu_sf_excedentes_de_cogeneracion_id'), table_name='indu_sf_excedentes_de_cogeneracion')
    op.drop_table('indu_sf_excedentes_de_cogeneracion')
    op.drop_index(op.f('ix_indu_sf_excedentes_de_autogeneracion_id'), table_name='indu_sf_excedentes_de_autogeneracion')
    op.drop_table('indu_sf_excedentes_de_autogeneracion')
    op.drop_index(op.f('ix_indu_sf_emision_de_sao_id'), table_name='indu_sf_emision_de_sao')
    op.drop_table('indu_sf_emision_de_sao')
    op.drop_index(op.f('ix_indu_sf_distribucion_segun_tipo_de_combustible_ladrilleras_id'), table_name='indu_sf_distribucion_segun_tipo_de_combustible_ladrilleras')
    op.drop_table('indu_sf_distribucion_segun_tipo_de_combustible_ladrilleras')
    op.drop_index(op.f('ix_indu_sf_capacidad_instalada_de_cogeneracion_id'), table_name='indu_sf_capacidad_instalada_de_cogeneracion')
    op.drop_table('indu_sf_capacidad_instalada_de_cogeneracion')
    op.drop_index(op.f('ix_indu_sf_capacidad_instalada_de_autogeneracion_id'), table_name='indu_sf_capacidad_instalada_de_autogeneracion')
    op.drop_table('indu_sf_capacidad_instalada_de_autogeneracion')
    op.drop_index(op.f('ix_indu_salidas_por_tipo_de_industria_energia_requerida_id'), table_name='indu_salidas_por_tipo_de_industria_energia_requerida')
    op.drop_table('indu_salidas_por_tipo_de_industria_energia_requerida')
    op.drop_index(op.f('ix_indu_salidas_por_tipo_de_industria_energia_producida_por_autogeneracion_y_cogeneracion_id'), table_name='indu_salidas_por_tipo_de_industria_energia_producida_por_autogeneracion_y_cogeneracion')
    op.drop_table('indu_salidas_por_tipo_de_industria_energia_producida_por_autogeneracion_y_cogeneracion')
    op.drop_index(op.f('ix_indu_salidas_por_tipo_de_industria_balance_total_de_la_energia_requerida_id'), table_name='indu_salidas_por_tipo_de_industria_balance_total_de_la_energia_requerida')
    op.drop_table('indu_salidas_por_tipo_de_industria_balance_total_de_la_energia_requerida')
    op.drop_index(op.f('ix_indu_salidas_por_combustible_energia_requerida_id'), table_name='indu_salidas_por_combustible_energia_requerida')
    op.drop_table('indu_salidas_por_combustible_energia_requerida')
    op.drop_index(op.f('ix_indu_salidas_por_combustible_energia_producida_por_autogeneracion_y_cogeneracion_id'), table_name='indu_salidas_por_combustible_energia_producida_por_autogeneracion_y_cogeneracion')
    op.drop_table('indu_salidas_por_combustible_energia_producida_por_autogeneracion_y_cogeneracion')
    op.drop_index(op.f('ix_indu_salidas_por_combustible_balance_total_de_la_energia_requerida_id'), table_name='indu_salidas_por_combustible_balance_total_de_la_energia_requerida')
    op.drop_table('indu_salidas_por_combustible_balance_total_de_la_energia_requerida')
    op.drop_index(op.f('ix_indu_emisiones_sao_id'), table_name='indu_emisiones_sao')
    op.drop_table('indu_emisiones_sao')
    op.drop_index(op.f('ix_indu_emisiones_por_el_consumo_de_bagazo_y_otros_id'), table_name='indu_emisiones_por_el_consumo_de_bagazo_y_otros')
    op.drop_table('indu_emisiones_por_el_consumo_de_bagazo_y_otros')
    op.drop_index(op.f('ix_indu_emisiones_gases_efecto_invernadero_id'), table_name='indu_emisiones_gases_efecto_invernadero')
    op.drop_table('indu_emisiones_gases_efecto_invernadero')
    # ### end Alembic commands ###
